name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main  # Deploy whenever you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/var/www/pythonapp"

      - name: Restart Flask app with PM2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Go to project directory
            cd /var/www/pythonapp

            # Activate virtual environment
            source venv/bin/activate

            # Upgrade pip and install dependencies
            pip install --upgrade pip
            pip install -r requirements.txt

            # Restart app if already running, otherwise start a new one
            pm2 restart flask-app || pm2 start "python3 app.py" --name flask-app

            # Save PM2 process list
            pm2 save
